global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'demo_go_site'
    static_configs:
      - targets: [ '192.168.1.118:9000' ]
    tls_config:
      insecure_skip_verify: true
    metrics_path: /metrics


